train_mode: triplet_align #train_classifier
setup_name: align_encoder_test
name: train_${train_mode}_${setup_name}_ch_sampling
chkpt_dir: /${oc.env:CHECKPOINT}/${oc.env:JOB_ID}

seed: 42
img_size: 256

data:
  n_classes: 6
  use_skip: False
  channels: [path_T2,path_ADC,path_HBV]
  missing_channel_mode: zeros
  target: isup6 #isup3", "isupc3", "isup6", "binary_low_high", "binary_all
  folds_train: [0,1,2,3]
  folds_val: [4]
  folds_test: None
  batch_size: 24
  pos_ratio: 0.33
  num_workers: 8
  pct_lower: 0.5
  pct_upper: 99.5
  img_size: ${img_size}
  histo_provider: all
  histo_marksheet_dir: /project/aip-medilab/shared/picai/histopathology_encodings/UNI2_splits
  histo_emb_dir: /home/obed/projects/aip-medilab/shared/picai/histopathology_encodings/gigapath/embeddings_512/all_splits
  mri_manifest: /project/aip-medilab/shared/picai/manifests/slices_manifest.csv

model:
  proj_dim: 512
  img_size: ${img_size}
  attn_dim: 512
  mean: [0, 0, 0] #[0.485, 0.456, 0.406]  # image_net's own, usually works fine
  std: [1, 1, 1] #[0.229, 0.224, 0.225] # image_net's own

align:
  triplet_epochs: 40
  triplet_patience: 20
  triplet_margin: 1
  triplet_lr: 3e-4
  triplet_wd: 0.01
  enc_lr_mult: 0.1 #Encoder LR = triplet_lr * enc_lr_mult
  logreg_max_iter: 50000
  checkpoint_dir: ${chkpt_dir}
  n_classes: ${data.n_classes}

head:
  head_epochs: 40
  head_patience: 20
  head_lr: 1e-3
  enc_lr_mult: ${align.enc_lr_mult}
  head_wd: 0.01
  head_scope: head_and_proj #head_only, head_and_proj, all
  head_dropout: 0.1
  head_hidden: 512
  checkpoint_dir: ${chkpt_dir}

wandb:
  name: ${name}
  project: mri_histopathology alignment
  group: ${train_mode}




